services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1g
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
